package probe

import (
	"context"
	"os"
	"path/filepath"
	"sync"

	"devlemon/internal/config"
	"devlemon/internal/i18n"
	"devlemon/internal/model"
)

type AppCacheProbe struct{}

func NewAppCacheProbe() *AppCacheProbe {
	return &AppCacheProbe{}
}

func (p *AppCacheProbe) Name() string {
	return "Application Garbage & Caches Probe"
}

func (p *AppCacheProbe) Category() model.Category {
	return model.CategoryAppCache
}

type appSpec struct {
	id          string
	title       string
	description string
	risk        model.RiskLevel
	paths       []string // 多个候选路径或子路径
	minSize     int64
}

func (p *AppCacheProbe) Scan(ctx context.Context, cfg *config.Config) (*model.Group, error) {
	group := &model.Group{
		ID:       "app_caches",
		Title:    i18n.T("📱 Application Caches & Garbage", "📱 应用垃圾与缓存（Xcode、VSCode、微信、办公影音）"),
		Category: model.CategoryAppCache,
		Items:    make([]*model.Item, 0),
	}

	home, err := os.UserHomeDir()
	if err != nil {
		return group, nil
	}

	knownAppSpecs := []appSpec{
		// 1. Xcode 开发垃圾
		{
			id:          "xcode_derived_data",
			title:       i18n.T("Xcode DerivedData", "Xcode 项目中间构建产物 (DerivedData)"),
			description: i18n.T("Intermediate build files and indexing caches generated by Xcode, safe to clean and will rebuild on next compile", "Xcode 编译项目产生的历史中间产物与索引，删除无破坏性，下次编译按需重新生成"),
			risk:        model.RiskRebuildable,
			paths: []string{
				filepath.Join(home, "Library", "Developer", "Xcode", "DerivedData"),
			},
			minSize: 10 * 1024 * 1024,
		},
		{
			id:          "xcode_device_logs",
			title:       i18n.T("Xcode iOS Device Logs", "Xcode 真机调试崩溃日志 (iOS DeviceLogs)"),
			description: i18n.T("Crash logs synchronized from connected iOS devices", "真机联调同步到本地的 iOS 设备历史运行与崩溃诊断日志"),
			risk:        model.RiskRebuildable,
			paths: []string{
				filepath.Join(home, "Library", "Developer", "Xcode", "iOS DeviceLogs"),
			},
			minSize: 5 * 1024 * 1024,
		},
		// 2. VSCode 缓存与日志
		{
			id:          "vscode_cache",
			title:       i18n.T("Visual Studio Code Cache & Logs", "Visual Studio Code 缓存与运行日志"),
			description: i18n.T("VSCode runtime cache, VSIX extension downloads, and logs", "VSCode 运行数据缓存、扩展安装缓存及运行日志，清理后按需重建"),
			risk:        model.RiskRebuildable,
			paths: []string{
				filepath.Join(home, "Library", "Caches", "com.microsoft.VSCode"),
				filepath.Join(home, "Library", "Application Support", "Code", "Cache"),
				filepath.Join(home, "Library", "Application Support", "Code", "CachedData"),
				filepath.Join(home, "Library", "Application Support", "Code", "CachedExtensionVSIXs"),
				filepath.Join(home, "Library", "Application Support", "Code", "logs"),
			},
			minSize: 5 * 1024 * 1024,
		},

		// 3. Codex 客户端界面渲染与 V8 字节码缓存 (严格物理隔离，绝不碰触 ~/.codex 会话历史与 CodexBar 账单)
		{
			id:          "codex_ui_cache",
			title:       i18n.T("Codex Client UI & Render Cache", "Codex 桌面端界面渲染与 V8 脚本缓存"),
			description: i18n.T("Electron frontend render cache and V8 script bytecode. Strictly excludes ~/.codex (all conversation threads, prompts, and memories) and CodexBar (token usage database)", "Electron 前端界面渲染缓存与 V8 脚本字节码。严格隔离保护 ~/.codex（全部会话历史、Prompt 与记忆资产）及 CodexBar（Token 账单数据库）"),
			risk:        model.RiskRebuildable,
			paths: []string{
				filepath.Join(home, "Library", "Caches", "Codex"),
			},
			minSize: 30 * 1024 * 1024,
		},

		// 4. 微信 WeChat (绝对安全子路径探测，严禁碰触 users/mmkv/xwechat_files 聊天与凭证数据)
		{
			id:          "wechat_app_cache",
			title:       i18n.T("WeChat Web & Media Cache", "微信 离线网页与临时媒体缓存"),
			description: i18n.T("Temporary web resources, image previews, and mini-program caches. Never touches chat history databases or login credentials (mmkv/users)", "微信内置浏览器网页、公众号离线缓存与小程序临时图片。绝不触碰聊天记录数据库及用户登录凭证 (mmkv/users)"),
			risk:        model.RiskRebuildable,
			paths: []string{
				filepath.Join(home, "Library", "Containers", "com.tencent.xinWeChat", "Data", "Library", "Caches"),
				filepath.Join(home, "Library", "Caches", "com.tencent.xinWeChat"),
				filepath.Join(home, "Library", "Containers", "com.tencent.xinWeChat", "Data", "Documents", "app_data", "radium", "cache"),
				filepath.Join(home, "Library", "Containers", "com.tencent.xinWeChat", "Data", "Documents", "app_data", "radium", "web"),
				filepath.Join(home, "Library", "Containers", "com.tencent.xinWeChat", "Data", "tmp", "wmpf_images"),
				filepath.Join(home, "Library", "Containers", "com.tencent.xinWeChat", "Data", "tmp", "wmpf_files"),
				filepath.Join(home, "Library", "Containers", "com.tencent.xinWeChat", "Data", "tmp", "TemporaryItems"),
			},
			minSize: 5 * 1024 * 1024,
		},
		// 7. 企业微信 WeCom
		{
			id:          "wework_cache",
			title:       i18n.T("WeCom (Enterprise WeChat) Cache", "企业微信 临时运行与媒体缓存"),
			description: i18n.T("Temporary document preview, image thumbnails, and web caches in WeCom", "企业微信临时文档预览、图片缩略图及网页渲染缓存"),
			risk:        model.RiskRebuildable,
			paths: []string{
				filepath.Join(home, "Library", "Containers", "com.tencent.WeWorkMac", "Data", "Library", "Caches"),
			},
			minSize: 2 * 1024 * 1024,
		},
		// 8. 钉钉 DingTalk
		{
			id:          "dingtalk_cache",
			title:       i18n.T("DingTalk Cache", "钉钉 客户端缓存与临时文件"),
			description: i18n.T("Temporary web resources and media caches in DingTalk", "钉钉网页离线缓存与多媒体传输临时文件"),
			risk:        model.RiskRebuildable,
			paths: []string{
				filepath.Join(home, "Library", "Containers", "com.alibaba.DingTalkMac", "Data", "Library", "Caches"),
				filepath.Join(home, "Library", "Application Support", "DingTalkMac", "Cache"),
			},
			minSize: 10 * 1024 * 1024,
		},
		// 9. 飞书 Lark / Feishu
		{
			id:          "feishu_cache",
			title:       i18n.T("Feishu / Lark Cache", "飞书 客户端离线缓存与日志"),
			description: i18n.T("Web container cache and offline resources in Feishu", "飞书文档离线缓存、网页容器资源及日志文件"),
			risk:        model.RiskRebuildable,
			paths: []string{
				filepath.Join(home, "Library", "Containers", "com.electron.lark", "Data", "Library", "Caches"),
				filepath.Join(home, "Library", "Containers", "com.bytedance.ee.lark", "Data", "Library", "Caches"),
			},
			minSize: 10 * 1024 * 1024,
		},
		// 10. QQ 音乐
		{
			id:          "qqmusic_cache",
			title:       i18n.T("QQ Music Offline Song & Cover Cache", "QQ 音乐 离线试听与封面缓存"),
			description: i18n.T("Album cover art and temporary audio streaming caches", "试听音乐的临时音频分片与专辑封面缩略图缓存"),
			risk:        model.RiskRebuildable,
			paths: []string{
				filepath.Join(home, "Library", "Containers", "com.tencent.QQMusicMac", "Data", "Library", "Caches"),
			},
			minSize: 10 * 1024 * 1024,
		},
		// 11. 网易云音乐
		{
			id:          "netease_music_cache",
			title:       i18n.T("Netease Music Audio & Cover Cache", "网易云音乐 试听缓存与封面"),
			description: i18n.T("Cached streaming audio and cover graphics in Netease Music", "网易云音乐客户端试听缓存、离线歌词与封面图"),
			risk:        model.RiskRebuildable,
			paths: []string{
				filepath.Join(home, "Library", "Caches", "com.netease.163music"),
			},
			minSize: 10 * 1024 * 1024,
		},
		// 12. 腾讯 QQ
		{
			id:          "qq_app_cache",
			title:       i18n.T("Tencent QQ Temporary Cache", "腾讯 QQ 临时图片与表情缓存"),
			description: i18n.T("Temporary image, sticker, and web view caches for Tencent QQ", "QQ 聊天表情包缩略图与内置网页缓存"),
			risk:        model.RiskRebuildable,
			paths: []string{
				filepath.Join(home, "Library", "Containers", "com.tencent.qq", "Data", "Library", "Caches"),
			},
			minSize: 10 * 1024 * 1024,
		},
		// 13. Apple Mail 邮件客户端缓存
		{
			id:          "apple_mail_cache",
			title:       i18n.T("Apple Mail Attachment & Data Cache", "系统邮件 (Mail) 离线附件与数据缓存"),
			description: i18n.T("Downloaded mail attachments and offline web caches in Apple Mail", "邮件客户端自动拉取的邮件附件预览与临时缓存，清理后重新联网自动同步"),
			risk:        model.RiskRebuildable,
			paths: []string{
				filepath.Join(home, "Library", "Containers", "com.apple.mail", "Data", "Library", "Caches"),
			},
			minSize: 5 * 1024 * 1024,
		},
	}

	var mu sync.Mutex
	var wg sync.WaitGroup

	for _, spec := range knownAppSpecs {
		spec := spec
		wg.Add(1)
		go func() {
			defer wg.Done()
			select {
			case <-ctx.Done():
				return
			default:
			}

			var totalSize int64
			var validPaths []string

			for _, p := range spec.paths {
				info, err := os.Stat(p)
				if err != nil || !info.IsDir() {
					continue
				}
				sz := FastDirSize(p)
				if sz > 0 {
					totalSize += sz
					validPaths = append(validPaths, p)
				}
			}

			if totalSize >= spec.minSize && len(validPaths) > 0 {
				primaryPath := validPaths[0]
				item := &model.Item{
					ID:            spec.id,
					Title:         spec.title,
					Description:   spec.description,
					Path:          primaryPath,
					SizeBytes:     totalSize,
					SizeFormatted: model.FormatBytes(totalSize),
					Risk:          spec.risk,
					Category:      model.CategoryAppCache,
					IsProtected:   false,
					CleanType:     model.CleanTypeRemovePath,
					CleanPath:     primaryPath,
				}

				// 如果有多个子路径，生成符合 shell 的清理指令
				if len(validPaths) > 1 {
					item.CleanType = model.CleanTypeCommand
					args := []string{"rm", "-rf"}
					args = append(args, validPaths...)
					item.CleanCommand = args
				}

				mu.Lock()
				group.Items = append(group.Items, item)
				group.TotalSizeBytes += totalSize
				group.TotalReclaimableBytes += totalSize
				mu.Unlock()
			}
		}()
	}

	wg.Wait()

	return group, nil
}


